apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mediawiki.fullname" . }}
data:
  MEDIAWIKI_SECRET_KEY: "589ba1f285a59d2515345c52a5820d4d1da4ef2cae3ff3471400bef23c39ec7b"
  MEDIAWIKI_SITE_NAME: "devops"
  MEDIAWIKI_LANGUAGE_CODE: "en"
  MEDIAWIKI_ADMIN_USER: "admin"
  MEDIAWIKI_ADMIN_PASS: "test12345678*"
  MEDIAWIKI_UPDATE: "true"
  MEDIAWIKI_SLEEP: "0"
  MEDIAWIKI_DB_TYPE: "mysql"
  MEDIAWIKI_DB_HOST: "10.0.120.151"
  MEDIAWIKI_DB_USER: "root"
  MEDIAWIKI_DB_PASSWORD: "test12345678*"
  MEDIAWIKI_DB_NAME: "devops_mediawiki"