apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediawiki-sql-database.fullname" . }}
  labels:
    {{- include "mediawiki-sql-database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    {{- include "mediawiki-sql-database.selectorLabels" . | nindent 4 }}
